<?php

namespace TOOLS\NerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NameEntityRecognitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NameEntityRecognitionRepository extends EntityRepository
{
}
