<?php

namespace TB\ModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestedItemResultRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestedItemResultRepository extends EntityRepository
{
}
