<?php

namespace DATA\PersonalPlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserSessionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserSessionsRepository extends EntityRepository
{
}
