cas_administration_user_index:
    path:     /utilisateurs
    defaults: { _controller: CASAdministrationBundle:User:index }

cas_administration_user_view:
    path:     /utilisateur/voir/{id}
    defaults: { _controller: CASAdministrationBundle:User:view }
    requirements:
        id:  \d+

