<?php

namespace CAS\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserPreferencesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserPreferencesRepository extends EntityRepository
{
}
