tb_personalplace_home_index:
    path:     /profile/testedGame/
    defaults: { _controller: TBPersonalPlaceBundle:Home:index }

tb_personalplace_public_index:
    path:     /utilisateur/{user_id}
    defaults: { _controller: TBPersonalPlaceBundle:Public:index }
    requirements:
        user_id: \d+
