tb_personalplace_home_index:
    path:     /profile/testedGame/
    defaults: { _controller: TBPersonalPlaceBundle:Home:index }

tb_personalplace_public_index:
    path:     /utilisateur/{user_id}
    defaults: { _controller: TBPersonalPlaceBundle:Public:index }
    requirements:
        user_id: \d+
        
# TestedGame administration :
tb_personalplace_testedgame_create:
    path:     /profile/testedGame/create
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:create }

tb_personalplace_testedgame_create_end:
    path:     /profile/testedGame/create/end/{testedGame_id}
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:createEnd }
    requirements:
        testedGame_id: \d+

tb_personalplace_testedgame_edit:
    path:     /profile/testedGame/edit/{testedGame_id}
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:edit }
    requirements:
        testedGame_id: \d+

tb_personalplace_testedgame_editIcon:
    path:     /profile/testedGame/edit-icon/{testedGame_id}
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:editIcon }
    requirements:
        testedGame_id: \d+

tb_personalplace_testedgame_addItems:
    path:     /profile/testedGame/add-items/{testedGame_id}
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:addItems }
    requirements:
        testedGame_id: \d+

tb_personalplace_testedgame_editItem:
    path:     /profile/testedGame/edit-item/{testedGame_id}/{testedItem_id}
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:editItem }
    requirements:
        testedGame_id: \d+
        testedItem_id: \d+

tb_personalplace_testedgame_removeItem:
    path:     /profile/testedGame/remove-item/{testedGame_id}/{testedItem_id}
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:removeItem }
    requirements:
        testedGame_id: \d+
        testedItem_id: \d+

tb_personalplace_testedgame_view:
    path:     /profile/testedGame/{testedGame_id}
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:view }
    requirements:
        testedGame_id: \d+

tb_personalplace_testedgame_updateOnlineStatus:
    path:     /profile/testedGame/updateOnlineStatus/{testedGame_id}
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:updateOnlineStatus }
    requirements:
        testedGame_id: \d+

tb_personalplace_testedgame_remove:
    path:     /profile/testedGame/remove/{testedGame_id}
    defaults: { _controller: TBPersonalPlaceBundle:TestedGame:remove }
    requirements:
        testedGame_id: \d+

