<?php

namespace DATA\TeachingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TeachingTestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeachingTestRepository extends EntityRepository
{
}
