<?php

namespace DATA\ImportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityFieldRepository extends EntityRepository
{
}
