<?php

namespace DATA\ImportBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityImportSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityImportSessionRepository extends EntityRepository
{
}
