<?php

namespace DATA\PublicBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReportingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportingRepository extends EntityRepository
{
}
