<?php

namespace DATA\DuplicateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GlobalWordTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalWordTypeRepository extends EntityRepository
{
}
