<?php

namespace DATA\DuplicateBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UnmatchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnmatchRepository extends EntityRepository
{
}
