<?php

namespace CLICHES\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ExcludeViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExcludeViewRepository extends EntityRepository
{
}
