<?php

namespace CLICHES\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerProposalFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerProposalFieldRepository extends EntityRepository
{
    public function countAll()
    {
        $queryNullValue = $this->createQueryBuilder('f')
            ->select('COUNT(f.id)')
            ->getQuery();
        return $queryNullValue->getSingleScalarResult();
    }

    public function countNull()
    {
        $queryNullValue = $this->createQueryBuilder('f')
            ->select('COUNT(f.id)')
            ->where('f.value is NULL')
            ->getQuery();
        return $queryNullValue->getSingleScalarResult();
    }

    public function countAllByField($field)
    {
        $queryNullValue = $this->createQueryBuilder('f')
            ->select('COUNT(f.id)')
            ->where('f.field = :field')
            ->setParameter('field', $field)
            ->getQuery();
        return $queryNullValue->getSingleScalarResult();
    }

    public function countNullByField($field)
    {
        $queryNullValue = $this->createQueryBuilder('f')
            ->select('COUNT(f.id)')
            ->where('f.value is NULL')
            ->andWhere('f.field = :field')
            ->setParameter('field', $field)
            ->getQuery();
        return $queryNullValue->getSingleScalarResult();
    }
}
