<?php

namespace CLICHES\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerErrorRepository extends EntityRepository
{
}
