<?php

namespace CLICHES\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerZoomViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerZoomViewRepository extends EntityRepository
{
}
