<?php

namespace CLICHES\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerProposalFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerProposalFieldRepository extends EntityRepository
{
}
