<?php

namespace CLICHES\PersonalPlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrivatePlayerEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivatePlayerEntityRepository extends EntityRepository
{
}
