<?php

namespace CLICHES\PersonalPlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrivatePlayerSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivatePlayerSessionRepository extends EntityRepository
{
}
