<?php

namespace CLICHES\PersonalPlaceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrivatePlayerViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrivatePlayerViewRepository extends EntityRepository
{
}
