<?php

namespace DATA\ImageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FileImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileImageRepository extends EntityRepository
{
}
