<?php

namespace DATA\ImageBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ViewRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViewRepository extends EntityRepository
{
    //Fonction comptant l'ensemble des vues :
    public function count() {
       return  $this->createQueryBuilder('u')
                    ->select('COUNT(u)')
                    ->getQuery()
                    ->getSingleScalarResult();
    }
    
    //Fonction retournant toutes les oeuvres valables pour une session
    public function searchAllView($session) {
        return $this->createQueryBuilder('u')
                    ->where('u.ecoleMatiere LIKE :matiere')
                    ->setParameter('matiere', $session->getSelectMatiere())
                    ->getQuery()
                    ->getResult()
        ;
    }
    
    //Fonction retournant le nombre de fois qu'une oeuvre est utilisé par une session
    public function countViewBySession($oeuvre, $session) {
        return $this->createQueryBuilder('a')
                    ->select('COUNT(u)')
                    ->from('HDAPlayerBundle:playerOeuvre', 'u')
                    ->where('u.playerSession = :playerSession')
                    ->setParameter('playerSession', $session)
                    ->andWhere('u.oeuvre = :oeuvre')
                    ->setParameter('oeuvre', $oeuvre)
                    ->getQuery()
                    ->getSingleScalarResult();
    }
    
    public function getRandView($session)
    {
        $oeuvre = NULL;
        $oeuvreFirst = $this->searchRandOeuvre($session);
        
        if($this->countOeuvreBySession($oeuvreFirst, $session) > 0)
        {
            foreach ($this->searchAllOeuvres($session) as $oeuvreByArray) {
                if($this->countOeuvreBySession($oeuvreByArray, $session) == 0) {
                    $oeuvre = $oeuvreByArray;
                }
            }
            if($oeuvre == $oeuvreFirst) {$oeuvre = NULL;}
        }
        else {$oeuvre = $oeuvreFirst;}

        return $oeuvre;
    }
}
