tb_administration_home_index:
    path:     /
    defaults: { _controller: TBAdministrationBundle:Home:index }

tb_administration_generate_generate:
    path:     /generate
    defaults: { _controller: TBAdministrationBundle:Generate:generate }

tb_administration_view_view:
    path:     /view/{id}
    defaults: { _controller: TBAdministrationBundle:View:view }
    requirements:
        id: \d+
