tb_administration_home_index:
    path:     /
    defaults: { _controller: TBAdministrationBundle:Home:index }

# TestedGame administration :
tb_administration_testedgame_create:
    path:     /testedGame/create
    defaults: { _controller: TBAdministrationBundle:TestedGame:create }

tb_administration_testedgame_edit:
    path:     /testedGame/edit/{testedGame_id}
    defaults: { _controller: TBAdministrationBundle:TestedGame:edit }
    requirements:
        testedGame_id: \d+

tb_administration_testedgame_editIcon:
    path:     /testedGame/edit-icon/{testedGame_id}
    defaults: { _controller: TBAdministrationBundle:TestedGame:editIcon }
    requirements:
        testedGame_id: \d+

tb_administration_testedgame_addItems:
    path:     /testedGame/add-items/{testedGame_id}
    defaults: { _controller: TBAdministrationBundle:TestedGame:addItems }
    requirements:
        testedGame_id: \d+

tb_administration_testedgame_view:
    path:     /testedGame/{testedGame_id}
    defaults: { _controller: TBAdministrationBundle:TestedGame:view }
    requirements:
        testedGame_id: \d+

tb_administration_testedgame_updateOnlineStatus:
    path:     /testedGame/updateOnlineStatus/{testedGame_id}
    defaults: { _controller: TBAdministrationBundle:TestedGame:updateOnlineStatus }
    requirements:
        testedGame_id: \d+

tb_administration_testedgame_remove:
    path:     /testedGame/remove/{testedGame_id}
    defaults: { _controller: TBAdministrationBundle:TestedGame:remove }
    requirements:
        testedGame_id: \d+

# TestedSession administration :
tb_administration_testedsession_index:
    path:     /testedSessions
    defaults: { _controller: TBAdministrationBundle:TestedSession:index }

tb_administration_testedsession_getByTestedGame:
    path:     /testedSession/getByTestedGame/{testedGame_id}
    defaults: { _controller: TBAdministrationBundle:TestedSession:getByTestedGame }
    requirements:
        testedGame_id: \d+

tb_administration_testedsession_view:
    path:     /testedSession/{testedSession_id}
    defaults: { _controller: TBAdministrationBundle:TestedSession:view }
    requirements:
        testedSession_id: \d+

