services:
    app.sitemap.all_contents_subscriber:
        class:     HOME\HomeBundle\EventListener\SitemapAllContentsSubscriber
        arguments:
            - "@router"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }