<?php

namespace DATA\SearchBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SearchIndexRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SearchIndexRepository extends EntityRepository
{
}
